#  House Price Prediction — Final Model

This notebook prepares the final machine learning pipeline for deployment.

## Objectives

- Load the Ames Housing dataset
- Recreate the preprocessing pipeline
- Configure the selected XGBoost model
- Train the final model
- Save the complete preprocessing + model pipeline
- Load the saved pipeline
- Verify that predictions work correctly
- Prepare the model for deployment

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

from xgboost import XGBRegressor

import joblib

In [2]:
PROJECT_ROOT=Path.cwd().parent

PROJECT_ROOT

WindowsPath('c:/Users/LENOVO/OneDrive/Desktop/Machine_Learning_Projects/house-price-prediction')

In [3]:
DATA_PATH=PROJECT_ROOT / "data" /"train.csv"

df=pd.read_csv(DATA_PATH)

df.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [4]:
TARGET="SalePrice"

X=df.drop(columns=[TARGET])

y=df[TARGET]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1460, 80)
y shape: (1460,)

In [5]:
numerical_features=X.select_dtypes(include=['int64','float64']).columns.tolist()

categorical_features=X.select_dtypes(include=['str']).columns.tolist()

print("Numerical features:", len(numerical_features))
print("Categorical features:", len(categorical_features))

Numerical features: 37
Categorical features: 43

In [7]:
numerical_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy='median')),
        ("scaler",StandardScaler())
    ]
)

categorical_pipeline=Pipeline(
    steps=[
        ("imputer",SimpleImputer(strategy='most_frequent')),
        ("encoder",OneHotEncoder(handle_unknown='ignore'))
    ]
)


preprocessor=ColumnTransformer(
    transformers=[
        ("num",numerical_pipeline,numerical_features),
        ("cat",categorical_pipeline,categorical_features)
    ]
)

In [8]:
final_xgb=XGBRegressor(
    n_estimators=700,
    learning_rate=0.1,
    max_depth=4,
    min_child_weight=5,
    subsample=0.7,
    colsample_bytree=0.7,
    objective="reg:squarederror",
    random_state=42
)

In [9]:
final_pipeline=Pipeline(
    steps=[
        ("preprocessor",preprocessor),
        ("model",final_xgb)
    ]
)

In [10]:
final_pipeline.fit(X,y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Id', 'MSSubClass',
                                                   'LotFrontage', 'LotArea',
                                                   'OverallQual', 'OverallCond',
                                                   'YearBuilt', 'YearRemodAdd',
                                                   'MasVnrArea', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', '1stFlrSF',
                                                   '2ndFlrSF', 'Lo...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=4, max_leaves=None, min_child_weight=5,
                              missing=nan, monotone_constraints=None,
                              multi_strategy=None, n_estimators=700,
                              n_jobs=None, num_parallel_tree=None, ...))])

In [13]:
sample_houses=X.iloc[:5]
sample_houses

   Id  MSSubClass MSZoning  LotFrontage  ...  MoSold YrSold SaleType SaleCondition
0   1          60       RL         65.0  ...       2   2008       WD        Normal
1   2          20       RL         80.0  ...       5   2007       WD        Normal
2   3          60       RL         68.0  ...       9   2008       WD        Normal
3   4          70       RL         60.0  ...       2   2006       WD       Abnorml
4   5          60       RL         84.0  ...      12   2008       WD        Normal

[5 rows x 80 columns]

In [14]:
sample_predictions=final_pipeline.predict(sample_houses)

sample_predictions

array([206750.38, 181504.34, 225130.2 , 140882.05, 252578.  ],
      dtype=float32)

In [19]:
comparison=pd.DataFrame({
    "Actual":y.iloc[:5].values,
    "Predicted":sample_predictions
})
comparison

   Actual      Predicted
0  208500  206750.375000
1  181500  181504.343750
2  223500  225130.203125
3  140000  140882.046875
4  250000  252578.000000

In [21]:
MODEL_DIR=PROJECT_ROOT/"models"

MODEL_DIR.mkdir(exist_ok=True)

MODEL_DIR

WindowsPath('c:/Users/LENOVO/OneDrive/Desktop/Machine_Learning_Projects/house-price-prediction/models')

In [22]:
MODEL_PATH=MODEL_DIR/"house_price_model.pkl"

joblib.dump(final_pipeline,MODEL_PATH)

print("Model saved to: ")
print(MODEL_PATH)

Model saved to:
c:\Users\LENOVO\OneDrive\Desktop\Machine_Learning_Projects\house-price-prediction\models\house_price_model.pkl

In [24]:
loaded_model=joblib.load(MODEL_PATH)
loaded_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Id', 'MSSubClass',
                                                   'LotFrontage', 'LotArea',
                                                   'OverallQual', 'OverallCond',
                                                   'YearBuilt', 'YearRemodAdd',
                                                   'MasVnrArea', 'BsmtFinSF1',
                                                   'BsmtFinSF2', 'BsmtUnfSF',
                                                   'TotalBsmtSF', '1stFlrSF',
                                                   '2ndFlrSF', 'Lo...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=4, max_leaves=None, min_child_weight=5,
                              missing=nan, monotone_constraints=None,
                              multi_strategy=None, n_estimators=700,
                              n_jobs=None, num_parallel_tree=None, ...))])

In [25]:
loaded_predictions=loaded_model.predict(sample_houses)

loaded_predictions

array([206750.38, 181504.34, 225130.2 , 140882.05, 252578.  ],
      dtype=float32)

In [26]:
np.allclose(sample_predictions,loaded_predictions)

True

In [30]:
# test with a new random house

test_house=X.iloc[[0]].copy()

test_house['OverallQual']=8
test_house['GrLivArea']=2000
test_house['GarageCars']=2
test_house['YearBuilt']=2010

In [39]:
test_price=loaded_model.predict(test_house)

print(f"Predicted house price: ${test_price[0]:,.2f}")

Predicted house price: $250,844.05

In [40]:
test_price

array([250844.05], dtype=float32)

In [41]:
FEATURE_PATH=MODEL_DIR/"feature_names.pkl"

joblib.dump(X.columns.tolist(),FEATURE_PATH)

print("Feature names saved.")

Feature names saved.

In [42]:
import sys

!{sys.executable} -m pip install joblib

Requirement already satisfied: joblib in c:\users\lenovo\onedrive\desktop\machine_learning_projects\house-price-prediction\.venv\lib\site-packages (1.6.0)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\lenovo\onedrive\desktop\machine_learning_projects\house-price-prediction\.venv\lib\site-packages (from joblib) (3.1.2)

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip